export const GET_REPOS_REQUEST = 'GET_REPOS_REQUEST'
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS'
export const GET_REPOS_FAILURE = 'GET_REPOS_FAILURE'

export const GET_COMMITS_REQUEST = 'GET_COMMITS_REQUEST'
export const GET_COMMITS_SUCCESS = 'GET_COMMITS_SUCCESS'
export const GET_COMMITS_FAILURE = 'GET_COMMITS_FAILURE'
